apiVersion: v1
kind: Service
metadata:
  name: {{ template "servicename" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
#  annotations:
#    prometheus.io/scrape: 'true'
#    prometheus.io/port: '8180'
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: {{ template "fullname" . }}
